//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPM
{
    public partial class PolicyHolderInquiry
    {
        protected global::System.Web.UI.WebControls.HiddenField hdnToken;
        protected global::System.Web.UI.WebControls.HiddenField hdnHasContext;
    }
}
